server {
    listen 80;
    server_name  _;
    root /usr/share/nginx/html;


   location /index.html {
        add_header Cache-Control "no-cache, no-store";
    }


   location ~ \.(css|js|gif|jpg|jpeg|png|svg|ico)$ {
        try_files $uri =404;
    }


    location / {
        access_log /var/log/nginx/web.access.log;
        error_log /var/log/nginx/web.error.log;
        try_files $uri $uri/ /index.html;
    }
}




